name: Deploy to AWS EC2

on:
  push:
    branches:
      - develop 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Paso 3: Conectarse al servidor EC2 vía SSH y desplegar
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}       
          username: ${{ secrets.EC2_USER }}   
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd demo-rate-limiting
            npm install
            git pull origin develop
            npm start
